backend:
  name: git-gateway
  branch: main # Vérifie que ta branche GitHub s'appelle bien main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "videos"
    label: "Mes Vidéos"
    folder: "_videos"
    create: true
    slug: "{{fields.title}}"
    fields:
      - {label: "Titre de la vidéo", name: "title", widget: "string"}
      - {label: "ID de la vidéo YouTube (ex: dQw4w9WgXcQ)", name: "youtube_id", widget: "string"}
      - {label: "Type de format", name: "format", widget: "select", options: ["Court (Vertical)", "Long (Horizontal)"]}